# -*- coding: utf-8 -*-
"""Practical-02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hLkzze6NDOPPiqLxOXvdAgKKFe6t-qfT

## Part A
Use fundamentals of Numpy and Pandas
1. Read the three csv files which contains the score of same students in term1 for each Subject
2. Remove the name and ethnicity column (to ensure confidentiality)
3. Fill missing score data with zero
4. Merge two files
5. Change Sex(M/F) Column to 1/2 for further analysis
6. Store the data in new file –ScoreFinal.csv
7. Convert ethnicity to numerical value
8. Fill the missing score for a student to the average of the class
"""

!pip install numpy
!pip install pandas

import pandas as pd

df_subject1 = pd.read_csv('/content/DSScoreTerm1.csv')
df_subject2 = pd.read_csv('/content/MathScoreTerm1.csv')
df_subject3 = pd.read_csv('/content/PhysicsScoreTerm1.csv')

df_merged = pd.merge(df_subject1, df_subject2, on='ID')
df_merged = pd.merge(df_merged, df_subject3, on='ID')

df_subject1.drop(columns=['Name', 'Ethinicity'], inplace=True)
df_subject2.drop(columns=['Name', 'Ethinicity'], inplace=True)
df_subject3.drop(columns=['Name', 'Ethinicity'], inplace=True)

df_subject1.fillna(0, inplace=True)
df_subject2.fillna(0, inplace=True)
df_subject3.fillna(0, inplace=True)

df_merged['Sex'] = df_merged['Sex'].replace({'M': 1, 'F': 2})
df_merged['Sex_x'] = df_merged['Sex_x'].replace({'M': 1, 'F': 2})
df_merged['Sex_y'] = df_merged['Sex_y'].replace({'M': 1, 'F': 2})

df_merged.to_csv('ScoreFinal.csv', index=False)
print(df_merged)

ethnicity_mapping = {'White American': 1, 'European American': 2, 'African American': 3, 'Hispanic': 4, 'Other': 5}
df_merged['Ethinicity'] = df_merged['Ethinicity'].map(ethnicity_mapping)

for subject in ['Score_x', 'Score_y', 'Score']:
    df_merged[subject].fillna(df_merged[subject].mean(), inplace=True)

